name: binary_codec

description: Dart library for converting standard data types to a binary format and back

author: Stefan Zemljic <stefan.zemljic@protonmail.com>

version: 2.0.3

repository: https://github.com/stefan-on-git/pub_dev_binary_codec

homepage: https://github.com/stefan-on-git/pub_dev_binary_codec

environment:
  sdk: '>=2.12.0 <3.0.0'