name: binary_codec

description: Dart library for converting standard data types to a binary format and back

version: 2.0.3

repository: https://github.com/stefan-zemljic/pub_dev_binary_codec

homepage: https://github.com/stefan-zemljic/pub_dev_binary_codec

environment:
  sdk: '>=2.12.0 <3.0.0'